/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Rudy;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Rudy.Cliente;

public class Ejemplo extends javax.swing.JFrame {
    DefaultTableModel modelo=new DefaultTableModel();
    ArrayList <Cliente> listaEmpleado=new ArrayList <Cliente>();
    void cargarTabla(){
        modelo.addColumn("DNI");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("MES DE ESTANCIA");
        modelo.addColumn("DIA DE INICIO");
        modelo.addColumn("DIA FINAL");
        modelo.addColumn("METODO DE PAGO");
        Tabla.setModel(modelo);
    }
    private void llenar(){
        for (int i=0;i<listaEmpleado.size();i++){
            modelo.addRow(new Object[]{listaEmpleado.get(i).getDni(),listaEmpleado.get(i).getNombre(),listaEmpleado.get(i).getApellido(),listaEmpleado.get(i).getTele(),listaEmpleado.get(i).getMes(),
            listaEmpleado.get(i).getDi(),listaEmpleado.get(i).getDf(),listaEmpleado.get(i).getMetodo()});}
    }
    private void limpiar(){
        int a=Tabla.getRowCount()-1;
        for (int i=a;i>=0;i--){
            modelo.removeRow(modelo.getRowCount()-1);
        }
    }


    public Ejemplo() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTele = new javax.swing.JTextField();
        txtInicio = new javax.swing.JTextField();
        txtFinal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rdEfectivo = new javax.swing.JRadioButton();
        rdTarjeta = new javax.swing.JRadioButton();
        btInsertar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU CLIENTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 240, 40));

        jLabel2.setText("DNI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setText("NOMBRE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel4.setText("APELLIDO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel5.setText("MES DE ESTANCIA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiempre", "Octubre", "Noviembre", "Diciembre" }));
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 140, -1));

        jLabel6.setText("DIA DE INICIO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, 20));

        jLabel7.setText("DIA FINAL");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jLabel8.setText("TELEFONO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 690, 250));
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 180, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 170, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 190, -1));
        getContentPane().add(txtTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 170, -1));
        getContentPane().add(txtInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 140, -1));
        getContentPane().add(txtFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 150, -1));

        jLabel9.setText("METODO DE PAGO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        buttonGroup1.add(rdEfectivo);
        rdEfectivo.setText("Efectivo");
        getContentPane().add(rdEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        buttonGroup1.add(rdTarjeta);
        rdTarjeta.setText("Tarjeta");
        getContentPane().add(rdTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        btInsertar.setText("Insertar");
        btInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertarActionPerformed
        // TODO add your handling code here:

        Cliente nuevo=new Cliente();
        nuevo.setDni(txtDNI.getText());
        nuevo.setNombre(txtNombre.getText());
        nuevo.setApellido(txtApellido.getText());
        nuevo.setTele(txtTele.getText());
        nuevo.setMes(combo.getSelectedItem().toString());
        nuevo.setDi(Integer.parseInt(txtInicio.getText()));
        nuevo.setDf(Integer.parseInt(txtFinal.getText()));
        if(rdEfectivo.isSelected())nuevo.setMetodo("Efectivo");
        if(rdTarjeta.isSelected())nuevo.setMetodo("Tarjeta");
        listaEmpleado.add(nuevo);
        limpiar();
        llenar();
    }//GEN-LAST:event_btInsertarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejemplo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btInsertar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdEfectivo;
    private javax.swing.JRadioButton rdTarjeta;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtFinal;
    private javax.swing.JTextField txtInicio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTele;
    // End of variables declaration//GEN-END:variables
}
